#!/usr/bin/env python3
"""Generate the protocol-v2 cross-language golden vectors.

Emits two artifacts from ONE definition of representative frames, using the
Python codec (control.protocol_v2) as the reference:

  * software/tests/data/protocol_v2_golden.json  — consumed by the pytest suite
  * firmware/controller/test/test_golden/golden_cases.h — embedded by the C test

Both C and Python must reproduce the recorded wire bytes byte-for-byte. CI runs
this script and `git diff --exit-code`s the outputs, so a codec change on either
side that drifts from the vectors fails the build.

Deterministic: no timestamps or randomness, so re-running yields identical files.
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
SOFTWARE_DIR = REPO_ROOT / "software"
sys.path.insert(0, str(SOFTWARE_DIR))

from control.protocol_v2 import frames  # noqa: E402

JSON_OUT = SOFTWARE_DIR / "tests" / "data" / "protocol_v2_golden.json"
HEADER_OUT = REPO_ROOT / "firmware" / "controller" / "test" / "test_golden" / "golden_cases.h"


def _pattern(n: int, seed: int) -> bytes:
    """Deterministic byte pattern that includes 0x00 bytes (exercises COBS)."""
    return bytes((i * 37 + seed) % 256 for i in range(n))


def golden_cases():
    """Representative frames: each system command + responses of varied size."""
    return [
        ("hello_request", frames.REQUEST, 1, frames.HELLO, 0, b""),
        ("get_info_request", frames.REQUEST, 2, frames.GET_INFO, 0, b""),
        ("get_state_request", frames.REQUEST, 3, frames.GET_STATE, 0, b""),
        ("diag_request_page0", frames.REQUEST, 4, frames.DIAG, 0, b"\x00"),
        ("diag_request_retry", frames.REQUEST, 5, frames.DIAG, frames.FLAG_RETRY, b"\x01"),
        # StandardResponse-sized payload with embedded zeros.
        ("std_response_with_zeros", frames.RESPONSE, 6, frames.GET_STATE, 0, _pattern(158, 3)),
        # Max payload -> multi-block COBS.
        ("max_payload_response", frames.RESPONSE, 7, frames.DIAG, 0, _pattern(frames.K_MAX_PAYLOAD, 7)),
        # All-zeros payload -> COBS worst case for zero runs.
        ("all_zeros_payload", frames.RESPONSE, 8, frames.GET_STATE, 0, b"\x00" * 32),
    ]


def build_records():
    records = []
    for name, ftype, cmd_id, cmd_type, flags, payload in golden_cases():
        frame = bytes([ftype, cmd_id, cmd_type, flags]) + payload
        crc = frames.crc16.crc16_ccitt(frame)
        decoded = frame + bytes([crc & 0xFF, (crc >> 8) & 0xFF])
        wire = frames.encode_frame(ftype, cmd_id, cmd_type, flags, payload)
        records.append(
            {
                "name": name,
                "type": ftype,
                "cmd_id": cmd_id,
                "cmd_type": cmd_type,
                "flags": flags,
                "payload": payload.hex(),
                "decoded": decoded.hex(),
                "wire": wire.hex(),
            }
        )
    return records


def write_json(records):
    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(JSON_OUT, "w") as f:
        json.dump(records, f, indent=2)
        f.write("\n")


def _c_byte_array(name, data):
    if not data:
        return f"static const uint8_t {name}[] = {{0}};  // empty (len 0)\n"
    lines = [f"static const uint8_t {name}[] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02X}" for b in data[i : i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines) + "\n"


def write_header(records):
    HEADER_OUT.parent.mkdir(parents=True, exist_ok=True)
    out = []
    out.append("// Generated by software/tools/gen_protocol_golden.py — DO NOT EDIT.")
    out.append("// Cross-language golden vectors; CI regenerates and git-diffs this file.")
    out.append("#ifndef GOLDEN_CASES_H")
    out.append("#define GOLDEN_CASES_H")
    out.append("")
    out.append("#include <stddef.h>")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("struct GoldenCase {")
    out.append("    const char* name;")
    out.append("    uint8_t type;")
    out.append("    uint8_t cmd_id;")
    out.append("    uint8_t cmd_type;")
    out.append("    uint8_t flags;")
    out.append("    const uint8_t* payload;")
    out.append("    size_t payload_len;")
    out.append("    const uint8_t* wire;")
    out.append("    size_t wire_len;")
    out.append("};")
    out.append("")

    for i, r in enumerate(records):
        payload = bytes.fromhex(r["payload"])
        wire = bytes.fromhex(r["wire"])
        out.append(_c_byte_array(f"kGoldenPayload{i}", payload))
        out.append(_c_byte_array(f"kGoldenWire{i}", wire))

    out.append("static const GoldenCase kGoldenCases[] = {")
    for i, r in enumerate(records):
        payload_len = len(bytes.fromhex(r["payload"]))
        wire_len = len(bytes.fromhex(r["wire"]))
        out.append(
            f'    {{"{r["name"]}", 0x{r["type"]:02X}, {r["cmd_id"]}, 0x{r["cmd_type"]:02X}, '
            f"0x{r['flags']:02X}, kGoldenPayload{i}, {payload_len}, kGoldenWire{i}, {wire_len}}},"
        )
    out.append("};")
    out.append("")
    out.append("static const size_t kNumGoldenCases = sizeof(kGoldenCases) / sizeof(kGoldenCases[0]);")
    out.append("")
    out.append("#endif  // GOLDEN_CASES_H")

    with open(HEADER_OUT, "w") as f:
        f.write("\n".join(out) + "\n")


def main():
    records = build_records()
    write_json(records)
    write_header(records)
    print(f"Wrote {len(records)} golden cases:")
    print(f"  {JSON_OUT}")
    print(f"  {HEADER_OUT}")


if __name__ == "__main__":
    main()
